pom.xml

- java.level is set to 7.
- Jenkins 1.612 establishes java.level to 6.
@reviewbybees @stephenc

Increase baseline version to one that sets 7 as its Java version

---

pom.xml

Just an ongoing update of the library.
Changelogs:
- 2.8.8: https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.8.8
- 2.8.9: https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.8.9
- 2.8.10: https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.8.10
Full diff:
- https://github.com/FasterXML/jackson-databind/compare/jackson-databind-2.8.7...jackson-databind-2.8.10
@reviewbybees @stephenc @ndeloof

Upgrade Parent POM to 3.2 and Jackson libs to 2.8.10

---

pom.xml

Alternative to #6 (CC @bsteph) which addresses CVE-2018-5968 and CVE-2018-7489 without updating to the 2.9.x line. Note that the issues in question are related to an opt-in feature in Jackson that is not used in any open source Jenkins plugin or Jenkins itself, so it should not be a vulnerability in practice.
We should still look into upgrading to 2.9.x, but first we need to do some testing to make sure that that line is compatible with the 2.8.x line so that plugins depending on this plugin do not break.
[Upstream changelog](https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.8) (see 2.8.11.1 in micro-patches section).
@reviewbybees

Update jackson-databind to 2.8.11.1

---

pom.xml

https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.9.9
Notably, this includes a fix for CVE-2019-12086. See
FasterXML/jackson-databind#2326 for details.
@reviewbybees

Update to Jackson 2.9.9

---

CHANGELOG.md
README.md
pom.xml

There is not a lot of Docs to move, but why not?

Move the plugin documentation from Wiki to GitHub

---

pom.xml

I'm trying to tidy the dependencies management on a plugin which has several (indirect) dependencies on various Jackson libraries. Most of the upper-bound issues (for Jackson) can be successfully solved by adding a dependency on `jackson2-api` before the other involved dependencies.
But I'm still facing this error, for `jackson-annotations` (because there is no direct `jackson-annotations` dependency in `jackson2-api`):
```
Failed while enforcing RequireUpperBoundDeps. The error(s) are [
Require upper bound dependencies error for com.fasterxml.jackson.core:jackson-annotations:2.9.5 paths to dependency are:
+-org.jenkins-ci.plugins:artifactory:3.8.x-SNAPSHOT
+-org.jfrog.artifactory.client:artifactory-java-client-services:2.6.2
+-com.fasterxml.jackson.core:jackson-annotations:2.9.5
and …
```

added dependency on jackson-annotations

---

pom.xml

jackson-datatype-json-org is used by pipeline-model-definition-plugin among others.

Add jackson-datatype-json-org

---

pom.xml
src/test/java/com/fasterxml/jackson/dataformat/xml/XmlMapperTest.java

Adds `jackson-dataformat-xml` to the Jackson 2 API plugin for the benefit of other plugins that need it and want to get it through the Jackson 2 API plugin. This also bundles the following two new transitive dependencies:
```
[WARNING] Bundling transitive dependency woodstox-core-6.2.4.jar (via jackson-dataformat-xml)
[WARNING] Bundling transitive dependency stax2-api-4.2.1.jar (via jackson-dataformat-xml)
```
These are up-to-date versions of StAX 2 (which the Java Platform does not provide) and Woodstox (the recommended StAX implementation for `jackson-dataformat-xml`.
I included a new integration test with `RealJenkinsRule` that works against Jenkins 2.297 and earlier, as well as tip-of-trunk with jenkinsci/jenkins#5604. Without jenkinsci/jenkins#5604, the test fails on tip-of-trunk …

Add `jackson-dataformat-xml` to Jackson 2 API plugin

---

pom.xml
src/test/java/com/fasterxml/jackson/dataformat/xml/XmlMapperTest.java

Testing Done: `mvn verify` passes with both the default Jenkins version and 2.300
CC @timja @jglick

Bump Jackson from 2.12.3 to 2.12.4

---

pom.xml

the activation framework classes are already provided by core.
Prior to jenkins-2.235 they where patched 1.1.1 versions but since
https://github.com/jenkinsci/jenkins/commit/abb131073ac06b2129cbda860c53d4720402a47f
it is the 1.2.1 version transitively from jakarta.mail
As the plugin is neither using plugin first classloader nor the
mask-classes approach this is just bloat - so remove it.
bumps the parent version and the minimum jenkins baseline to be > 2.235
to ensure we do get at least a 1.2.x version

do not bundle a library whose classes are already provideded by core

---

pom.xml

https://github.com/jenkinsci/jackson2-api-plugin/pull/94/commits/08b59d1c370395d5112355c0a2704e65111540f0 shows that dependabot currently is not keeping the plugin version aligned with the component version (which it does for caffeine and jjwt)
try and change so we do not use an intermediate property to see if that helps dependabot...

try and get dependabot to update the version when updating the dependency

---

pom.xml

This is used by the [GitLab](https://plugins.jenkins.io/gitlab-plugin/) plugin, so it would be nice to have it included in the Jackson 2 API plugin.

Add `jackson-jaxrs-json-provider`

---

pom.xml
src/test/java/com/fasterxml/jackson/jaxrs/json/JacksonJsonProviderTest.java

Fixes jenkinsci/gitlab-plugin#1206 by bundling the JAX-RS API JAR in the Jackson 2 API plugin. The new `RealJenkinsRule`-based test fails before this PR and passes with it. I have also written a functional test in jenkinsci/gitlab-plugin#1207 which fails before this PR and passes with it.

Fix `JacksonJsonProvider`

---

pom.xml

#107 added `jackson-jaxrs-json-provider`, which exposed the need for the JAX-RS API. That was added in #111, which exposed the need for a JAX-RS implementation. Since a JAX-RS API and implementation are outside the scope of this plugin, I have created a new [Jersey 2 API plugin](https://github.com/jenkinsci/jersey2-api-plugin/) providing the [JAX-RS 2.1](https://jcp.org/en/jsr/detail?id=370) API with [Jersey 2](https://eclipse-ee4j.github.io/jersey/) as its implementation. This PR adjusts the Jackson 2 API plugin to consume that new plugin as an optional dependency.

Use Jersey 2 API plugin

---

pom.xml

The various jackson libraries are not always version aligned and as such
using a single version prevents us from using the latest versions of
all jackson libraries.
Updating to use the jackson bom to allow pulling in some newer library
versions.

Switch to use the jackson bom and update to latest 2.13 versions

---

Jenkinsfile

Reverts jenkinsci/jackson2-api-plugin#172
Actually best not to do this - Jenkins the version we target uses java8 and as this is an API plugin that *may* contain some security issue that we need to release for (jackson may not provide backports) I think it is better to keep the status quo.

Revert "remove java8 build"

---

pom.xml

the byte-buddy library includes a shaded ASM lib, but there was no attribution of this in the plugin.
https://github.com/jenkinsci/jackson2-api-plugin/pull/267#issuecomment-2656029762
https://issues.jenkins.io/browse/JENKINS-75276
None

[JENKINS-75276] ensure ASM licence is attributes

---

pom.xml
src/test/java/com/fasterxml/jackson/dataformat/toml/TomlReadTest.java

This pull requests adds the TOML dataformat library to existing formats (XML, YAML, etc)
* Minimal change, just adds a library
* Basic Unit test added to ensure it works
* Manually tested on local instance
```[tasklist]
```

Add TOML DataFormat Support

---

pom.xml

Reverts jenkinsci/jackson2-api-plugin#267
jackson2 does not actually need byte-buddy.  this was an error upstream that was fixed in https://github.com/FasterXML/jackson-databind/pull/4491  (in 2.18)
So until we pick up that version lets not force the install of a plugin that would then be dangling when it is about to be removed. (quick fix just to prevent users getting the last release)

Revert "Use Byte Buddy library plugin where possible"

---

Jenkinsfile
pom.xml
src/test/java/com/fasterxml/jackson/dataformat/toml/TomlReadTest.java

Jenkins 2.479.1 provides Jakarta EE 9, Eclipse Jetty 12, Spring Security 6, and Java 17.
* Update plugin pom and baseline
* Remove deprecations
* Use Java 17 language features
* Minor cleanup
`mvn clean verify`

Require Jenkins 2.479.1 and Jakarta EE 9

---

pom.xml

nested-data-reporting plugin is not using the jackson2-api plugin as the dataformat-csv is missing
This adds this so the plugin will be able to use it in the future

add dep to jackson-dataformat-csv

---

pom.xml

Reverts jenkinsci/jackson2-api-plugin#284
See https://github.com/jenkinsci/bom/pull/5114
This keeps the main branch releasable at all times, a desirable property in case we need to release parent POM updates for PCT purposes or other reasons.
I'm intentionally not doing anything special with the version number here to avoid introducing technical debt. Users who have already upgraded won't get any new 2.18.x releases, but because we've stopped distribution of 2.19.x on the update center, those users should be very few.

Revert "Bump com.fasterxml.jackson:jackson-bom from 2.18.3 to 2.19.0"
